// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayGo.Data;

#nullable disable

namespace StayGo.Migrations
{
    [DbContext(typeof(StayGoContext))]
    partial class StayGoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StayGo.Models.Amenidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Amenidades");
                });

            modelBuilder.Entity("StayGo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropiedadSearchHistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchHistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StayGo.Models.ContactoMensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("StayGo.Models.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HabitacionId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("StayGo.Models.Favorito", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "PropiedadId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("StayGo.Models.Habitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Piso")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoCama")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("StayGo.Models.ImagenPropiedad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("ImagenesPropiedad");
                });

            modelBuilder.Entity("StayGo.Models.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("StayGo.Models.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Metodo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransaccionRef")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("StayGo.Models.Propiedad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("PrecioPorNoche")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrecioPorNoche");

                    b.HasIndex("Tipo", "Capacidad");

                    b.ToTable("Propiedades");
                });

            modelBuilder.Entity("StayGo.Models.PropiedadAmenidad", b =>
                {
                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AmenidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropiedadId", "AmenidadId");

                    b.HasIndex("AmenidadId");

                    b.ToTable("PropiedadAmenidades");
                });

            modelBuilder.Entity("StayGo.Models.Resena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("StayGo.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HabitacionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Huespedes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("StayGo.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StayGo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StayGo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StayGo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StayGo.Models.ContactoMensaje", b =>
                {
                    b.HasOne("StayGo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StayGo.Models.Disponibilidad", b =>
                {
                    b.HasOne("StayGo.Models.Habitacion", "Habitacion")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("StayGo.Models.Favorito", b =>
                {
                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("Favoritos")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.ApplicationUser", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.Usuario", null)
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Propiedad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StayGo.Models.Habitacion", b =>
                {
                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("Habitaciones")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("StayGo.Models.ImagenPropiedad", b =>
                {
                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("Imagenes")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("StayGo.Models.Pago", b =>
                {
                    b.HasOne("StayGo.Models.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("StayGo.Models.Propiedad", b =>
                {
                    b.OwnsOne("StayGo.Models.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("PropiedadId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Linea1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Linea2")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT");

                            b1.HasKey("PropiedadId");

                            b1.ToTable("Propiedades");

                            b1.WithOwner()
                                .HasForeignKey("PropiedadId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("StayGo.Models.PropiedadAmenidad", b =>
                {
                    b.HasOne("StayGo.Models.Amenidad", "Amenidad")
                        .WithMany("PropiedadAmenidades")
                        .HasForeignKey("AmenidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("PropiedadAmenidades")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenidad");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("StayGo.Models.Resena", b =>
                {
                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("Resenas")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.ApplicationUser", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.Usuario", null)
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Propiedad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StayGo.Models.Reserva", b =>
                {
                    b.HasOne("StayGo.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StayGo.Models.Propiedad", "Propiedad")
                        .WithMany("Reservas")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.ApplicationUser", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayGo.Models.Usuario", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Habitacion");

                    b.Navigation("Propiedad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StayGo.Models.Usuario", b =>
                {
                    b.HasOne("StayGo.Models.ApplicationUser", "IdentityUser")
                        .WithOne("Usuario")
                        .HasForeignKey("StayGo.Models.Usuario", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("StayGo.Models.Amenidad", b =>
                {
                    b.Navigation("PropiedadAmenidades");
                });

            modelBuilder.Entity("StayGo.Models.ApplicationUser", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StayGo.Models.Habitacion", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("StayGo.Models.Propiedad", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Favoritos");

                    b.Navigation("Habitaciones");

                    b.Navigation("Imagenes");

                    b.Navigation("PropiedadAmenidades");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("StayGo.Models.Reserva", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("StayGo.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
